# Generated by Django 5.2.4 on 2025-07-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('education', models.TextField(max_length=255)),
                ('previous_Experience', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/')),
            ],
        ),
    ]
